from .gcpanet import GCPANet
from .gcpa_gald import GCPAGALDNet
from .gcpa_gald_v2 import GCPAGALDNetv2
from .gcpa_gald_v3 import GCPAGALDNetv3
from .gcpa_gald_v4 import GCPAGALDNetv4
from .gcpa_gald_v5 import GCPAGALDNetv5
from .gcpa_gald_v6 import GCPAGALDNetv6
from .gcpa_gald_v7 import GCPAGALDNetv7
from .gcpa_gald_v8 import GCPAGALDNetv8
from .gcpa_gald_v9 import GCPAGALDNetv9
from .gcpa_aspp import GCPAASPPNet
from .gcpa_psp import GCPAPSPNet
from .gcpa_psp_s import GCPAPSPSmallNet
from .gcpa_psp_ag import GCPAPSPAGNet
from .gcpa_cc import GCPACCNet
from .gcpa_cc_v2 import GCPACCv2Net
from .gcpa_cc_v3 import GCPACCv3Net
from .gcpa_cc_v4 import GCPACCv4Net
from .gcpa_cc_v5 import GCPACCv5Net
from .gcpa_cc_dualpath import GCPACCDualNet
from .gcpa_cc_aspp import GCPACCASPPNet
from .gcpa_psp_agv2 import GCPAPSPAGv2Net
from .scws_cc import SCWSCCNet

