dataset:
  data_path: ../data/CHASE
  distill_label_path: ../results/SCWSRCCANet_Chase/PR_SCWSRCCANet/Soft
  train_data_path: 
    - ../data/CHASE/CHASE_Training_20
  test_data_path:
    - ../data/CHASE/CHASE_Test_8
    # - ../data/CHASE/CHASE_Training_20

  val_data_path:
    - ../data/CHASE/CHASE_Test_8
  fold: 5
 
model:
  # save_dir: /mnt/data/hungnt/snapshots/SCWSRCCANetDistillation_chase
  # save_dir: /mnt/data/hungnt/snapshots/SCWSRCCANetDistillation2_chase
  save_dir: /mnt/data/hungnt/snapshots/SCWSRCCANetDistillation960_chase

  # save_dir: ../snapshots/SCWSRCCANet_chase
  # save_dir: /mnt/data/hungnt/snapshots/SCWSRCCANet_chase_960
  arch: SCWSRCCANet  
  # arch: UNet  
  # arch: DUNet  
  arch_teacher: SCWSRCCANet
  # weight_teacher_path: ../snapshots/SCWSRCCANet_chase/PraNetDG-fold5-144.pth
  # weight_teacher_path: /mnt/data/hungnt/snapshots/SCWSRCCANet_chase_960/PraNetDG-fold5-139.pth

  save_from: 50
  start_from: 0
  num_epochs: 150

optimizer:
  name: adam
  lr: 0.0001
  clip: 0.5 
  scheduler: cosine_warmup
  num_warmup_epoch: 3
  loss: structure_loss
  # loss: bce_loss
  # loss: distillation_loss

train:
  fold: 5
  is_val: True
  size_rates:
    - 0.75
    - 1
    - 1.25
  dataloader:
    # name: ISICDistillationDataset

    name: ChaseDataset
    batchsize: 2
    shuffle : True
    img_size: 960
    pin_memory: True
    drop_last: True
  augment: 
    prob: 0.7

    Flip_prob: 0.7
    HueSaturationValue_prob: 0.7
    RandomBrightnessContrast_prob: 0.7
    crop_prob: 0.7

    randomrotate90_prob: 0.7
    # elastictransform_prob: 0.7
    # gridistortion_prob: 0.7
    # opticaldistortion_prob: 0.7
    # verticalflip_prob: 0.7
    # horizontalflip_prob: 0.7
    # randomgamma_prob: 0.7
    # CoarseDropout_prob: 0.7
    # RGBShift_prob: 0.7
    # MotionBlur_prob: 0.7
    # MedianBlur_prob: 0.7
    # GaussianBlur_prob: 0.7
    GaussNoise_prob: 0.7
    # ChannelShuffle_prob: 0.7
    ColorJitter_prob: 0.7



test:


  folds: 
    5: 
      - 144
      - 145
  dev: cuda
  visualize: False
  vis_x: 180
  vis_overwrite: True
  visualize_dir: ../results/SCWSRCCANet_Chase

  dataloader:
    name: ChaseDataset
    batchsize: 1
    shuffle : False
    img_size: 960
    pin_memory: True
    drop_last: True

  augment: 
    prob: 0

    Flip_prob: 0
    HueSaturationValue_prob: 0
    RandomBrightnessContrast_prob: 0
    crop_prob: 0

    randomrotate90_prob: 0
    elastictransform_prob: 0
    gridistortion_prob: 0
    opticaldistortion_prob: 0
    verticalflip_prob: 0
    horizontalflip_prob: 0
    randomgamma_prob: 0
    CoarseDropout_prob: 0
    RGBShift_prob: 0
    MotionBlur_prob: 0
    MedianBlur_prob: 0
    GaussianBlur_prob: 0
    GaussNoise_prob: 0
    ChannelShuffle_prob: 0

