
dataset:
  data_path: ../data/Kvasir_fold_new
  train_data_path: 
    - ../data/usnerve/TrainDataset

  test_data_path:
    # - /mnt/data/US-nerve/test/
    - ../data/usnerve/ValDataset

  val_data_path:
    - ../data/usnerve/ValDataset

  fold: 5
  img_size: 352     
 
model:
  save_dir: ../snapshots/GCPACCNet_USNERVE
  arch: GCPACCNet
  save_from: 150
  start_from: 0
  num_epochs: 200

optimizer:
  name: adam
  lr: 0.0001
  clip: 0.5
  scheduler: cosine_warmup    
  num_warmup_epoch: 5
  loss: structure_loss

train:
  fold: 5
  is_val: True
  size_rates:
    - 0.75
    - 1
    - 1.25
  dataloader:
    name: USNerveDataset
    batchsize: 30
    shuffle : True
    img_size: 352
    pin_memory: True
    drop_last: True
  augment: 
    prob: 0.7
    blur_prob: 0.7
    jitter_prob: 0.7
    rotate_prob: 0.7
    flip_prob: 0.7


test:
  # TRansUnet+ GALD
  # folds: 
  #   0: 
  #     - 137
  #   1: 
  #     - 149
  #   2: 
  #     - 185
  #   3: 
  #     - 158
  #   4: 
  #     - 101

  # GCPA + GALD
  # folds: 
  #   0: 
  #     - 95 
  #     # - 110
  #   1: 
  #     - 149
  #   2: 
  #     - 149
  #   3: 
  #     - 197
  #   4: 
  #     - 128 
  #     # - 110

  # GCPA + GALDv4
  # folds: 
  #   0: 
  #     - 140
  #   1: 
  #     - 170
  #   2: 
  #     - 149
  #   3: 
  #     - 98
  #   4: 
  #     - 152 

  # Pranetv8
  # folds: 
  #   0: 
  #     - 158
  #   1: 
  #   2: 
  #     - 149
  #   3: 
  #   4: 


  # PranetvGALD
  # folds: 
  #   0: 
  #     - 116
  #   1:
  #     - 197
  #   2: 
  #     - 140
  #   3:
  #     - 140
  #   4:
  #     - 191 

  folds: 
    # 0: 
    #   - 81
    #   - 199
    # 1: 
    #   - 81
    #   - 199
    # 2: 
    #   - 81
    #   - 199
    # 3: 
    #   - 190
    #   - 199
    # 4: 
    #   - 81
    #   - 199
    5: 
      - 23
      - 24
  visualize: True
  visualize_dir: ../results/GCPACCISIC_org
  vis_x: 180
  vis_overwrite: False
  dataloader:
    name: USNerveDataset
    batchsize: 1
    shuffle : False
    img_size: 352
    pin_memory: True
    drop_last: True

  augment: 
    prob: 0
    blur_prob: 0
    jitter_prob: 0
    rotate_prob: 0
    flip_prob: 0

