dataset:
  data_path: /mnt/data/hungnt/data/Kvasir_fold_new
  distill_label_path: ../results/SCWSRCCANet_Chase/PR_SCWSRCCANet/Soft
  train_data_path:
    - /mnt/data/hungnt/data/kvasir-seg/TrainDataset
    - /mnt/data/hungnt/data/kvasir-seg/ValDataset
    # - /mnt/data/hungnt/data/Kvasir_SEG/Kvasir_SEG_Training_880
    # - /mnt/data/hungnt/data/Kvasir_fold_new/fold_3
    # - /mnt/data/hungnt/data/Kvasir_fold_new/fold_1
    # - /mnt/data/hungnt/data/Kvasir_fold_new/fold_2
    # - /mnt/data/hungnt/data/Kvasir_fold_new/fold_4
  test_data_path:
    # - /mnt/data/hungnt/data/Kvasir_SEG/Kvasir_SEG_Validation_120
    # - /mnt/data/hungnt/data/Kvasir_fold_new/fold_0
    - /mnt/data/hungnt/data/kvasir-seg/TestDataset/Kvasir
    # - /mnt/data/hungnt/data/kvasir-seg/TestDataset/CVC-ColonDB
    # - /mnt/data/hungnt/data/kvasir-seg/TestDataset/CVC-ClinicDB
    # - /mnt/data/hungnt/data/kvasir-seg/TestDataset/ETIS-LaribPolypDB
    # - /mnt/data/hungnt/data/kvasir-seg/TestDataset/CVC-300
  val_data_path:
    # - /mnt/data/hungnt/data/kvasir-seg/ValDataset
    - /mnt/data/hungnt/data/kvasir-seg/TestDataset/Kvasir
    # - /mnt/data/hungnt/data/Kvasir_SEG/Kvasir_SEG_Validation_120
  fold: 5

model:
  save_dir: ../snapshots/GCPACGNLResNet_v1
  arch: GCPACGNLResNet
  arch_teacher: GCPACGNLResNet
  weight_teacher_path: ../snapshots/GCPACGNLResNet_v1
  save_from: 150
  start_from: 0
  num_epochs: 200

optimizer:
  name: adam
  lr: 0.0001
  clip: 0.5
  scheduler: cosine_warmup
  num_warmup_epoch: 8
  loss: structure_loss
  # loss: structure_ssim_loss
  # loss: distillation_loss
  # loss: bce_loss

train:
  fold: 5
  is_val: True
  size_rates:
    - 0.75
    - 1
    - 1.25
  dataloader:
    name: KvasirDataset
    batchsize: 12
    shuffle: True
    img_size: 352
    pin_memory: True
    drop_last: True
  augment:
    prob: 0.7
    Flip_prob: 0.7
    HueSaturationValue_prob: 0.7
    RandomBrightnessContrast_prob: 0.7
    crop_prob: 0.7
    randomrotate90_prob: 0.7
    # elastictransform_prob: 0.7
    # gridistortion_prob: 0.7
    # opticaldistortion_prob: 0.7
    # verticalflip_prob: 0.7
    # horizontalflip_prob: 0.7
    # randomgamma_prob: 0.7
    # CoarseDropout_prob: 0.7
    # RGBShift_prob: 0.7
    # MotionBlur_prob: 0.7
    # MedianBlur_prob: 0.7
    # GaussianBlur_prob: 0.7
    # GaussNoise_prob: 0.7
    # ChannelShuffle_prob: 0.7

test:
  folds:
    5:
      - 166
      - 167
  dev: cuda
  visualize: False
  visualize_dir: ../results/PraNet/Kvasir
  vis_x: 180
  vis_overwrite: False
  dataloader:
    name: KvasirDataset
    batchsize: 1
    shuffle: False
    img_size: 352
    pin_memory: True
    drop_last: True

  augment:
    # prob: 0
    # Flip_prob: 0
    # HueSaturationValue_prob: 0
    # RandomBrightnessContrast_prob: 0
    # crop_prob: 0
    # randomrotate90_prob: 0
    # elastictransform_prob: 0
    # gridistortion_prob: 0
    # opticaldistortion_prob: 0
    # verticalflip_prob: 0
    # horizontalflip_prob: 0
    # randomgamma_prob: 0
    # CoarseDropout_prob: 0
    # RGBShift_prob: 0
    # MotionBlur_prob: 0
    # MedianBlur_prob: 0
    # GaussianBlur_prob: 0
    # GaussNoise_prob: 0
    # ChannelShuffle_prob: 0
    
infer:
  models:
    - [GCPARCCANet , snapshots/GCPARCCA_v4/PraNetDG-fold5-199.pth]
    - [GCPAPSPNet , snapshots/GCPAPSPNet_kfold/PraNetDG-fold5-197.pth]
  vis_overwrite: False 
  vis_x: 180
  visualize_dir: ../outputs/infer
  compare_fig: compare.png
  compare_csv: compare.csv
  img_paths: 
    - /mnt/data/hungnt/data/kvasir-seg/TrainDataset/images/1.png
    - /mnt/data/hungnt/data/kvasir-seg/TrainDataset/images/27.png
    - /mnt/data/hungnt/data/kvasir-seg/TrainDataset/images/562.png
    - /mnt/data/hungnt/data/kvasir-seg/TrainDataset/images/75.png
  mask_paths:
    - /mnt/data/hungnt/data/kvasir-seg/TrainDataset/masks/1.png
    - /mnt/data/hungnt/data/kvasir-seg/TrainDataset/masks/27.png
    - /mnt/data/hungnt/data/kvasir-seg/TrainDataset/masks/562.png
    - /mnt/data/hungnt/data/kvasir-seg/TrainDataset/masks/75.png