dataset:
  data_path: ../data/ISIC2018_BCDU
  train_data_path: 
    - ../data/ISIC2018_BCDU/traindataset_352
    # - ../data/ISIC2018_BCDU/traindataset_352
    # - ../data/ISIC2018_BCDU/traindataset

  test_data_path:
    - ../data/ISIC2018_BCDU/testdataset_256
    # - ../data/ISIC2018_BCDU/testdataset
  val_data_path:
    - ../data/ISIC2018_BCDU/valdataset_256
    # - ../data/ISIC2018_BCDU/valdataset

  fold: 5
  img_size: 352     
 
model:
  save_dir: ../snapshots/SCWSRCCANet_ISICBCDU_352
  arch: SCWSRCCANet
  # arch: GCPAPSP2Net
  # arch: GCPAGALDNetv8
  # PraNetGALD
  # GCPAGALDNet
  save_from: 180
  start_from: 0
  num_epochs: 300

optimizer:
  name: adam
  lr: 0.0001
  clip: 0.5
  scheduler: cosine_warmup    
  num_warmup_epoch: 8
  loss: structure_loss
  # loss: FocalLoss

train:
  fold: 5
  is_val: True
  size_rates:
    - 0.75
    - 1
    - 1.25
  dataloader:
    name: ISICDataset
    batchsize: 20
    shuffle : True
    img_size: 352
    pin_memory: True
    drop_last: True
  augment: 
    prob: 0.7

    Flip_prob: 0.7
    HueSaturationValue_prob: 0
    RandomBrightnessContrast_prob: 0.7
    crop_prob: 0.7

    randomrotate90_prob: 0.7
    elastictransform_prob: 0
    gridistortion_prob: 0
    opticaldistortion_prob: 0
    verticalflip_prob: 0
    horizontalflip_prob: 0
    randomgamma_prob: 0
    CoarseDropout_prob: 0
    RGBShift_prob: 0
    MotionBlur_prob: 0
    MedianBlur_prob: 0
    GaussianBlur_prob: 0
    GaussNoise_prob: 0
    ChannelShuffle_prob: 0




test:
  folds: 
    5: 
      - 150
      - 300
  visualize: False
  dev: cuda
  visualize_dir: ../results/SCWSRCCANet_ISICBCDU
  vis_x: 180
  vis_overwrite: True
  dataloader:
    name: ISICDataset
    batchsize: 1
    shuffle : False
    img_size: 352
    pin_memory: True
    drop_last: True

  augment: 
    prob: 0

    Flip_prob: 0
    HueSaturationValue_prob: 0
    RandomBrightnessContrast_prob: 0
    crop_prob: 0

    randomrotate90_prob: 0
    elastictransform_prob: 0
    gridistortion_prob: 0
    opticaldistortion_prob: 0
    verticalflip_prob: 0
    horizontalflip_prob: 0
    randomgamma_prob: 0
    CoarseDropout_prob: 0
    RGBShift_prob: 0
    MotionBlur_prob: 0
    MedianBlur_prob: 0
    GaussianBlur_prob: 0
    GaussNoise_prob: 0
    ChannelShuffle_prob: 0



