dataset:
  data_path: ../data/ISIC2018_BCDU
  train_data_path: 
    # - ../data/ISIC2018_Task1/traindataset_aug_352
    - ../data/ISIC2018_BCDU/traindataset
    # - ../data/ISIC2018_Task1/traindataset
    # - ../data/ISIC2018_Task1/valdataset

  test_data_path:
    - ../data/ISIC2018_BCDU/testdataset
  val_data_path:
    - ../data/ISIC2018_BCDU/valdataset

  fold: 5
  img_size: 352     
 
model:
  save_dir: ../snapshots/SCWSRCCANet_ISIC
  arch: SCWSRCCANet
  # arch: GCPAGALDNetv8
  # PraNetGALD
  # GCPAGALDNet
  save_from: 1
  start_from: 0
  num_epochs: 300

optimizer:
  name: adam
  lr: 0.0001
  clip: 0.5
  scheduler: cosine_warmup    
  num_warmup_epoch: 8
  loss: structure_loss

train:
  fold: 5
  is_val: True
  size_rates:
    - 0.75
    - 1
    - 1.25
  dataloader:
    name: ISICDataset
    batchsize: 20
    shuffle : True
    img_size: 352
    pin_memory: True
    drop_last: True
  augment: 
    prob: 0.7

    Flip_prob: 0.7
    HueSaturationValue_prob: 0.7
    RandomBrightnessContrast_prob: 0.7
    crop_prob: 0.7

    randomrotate90_prob: 0
    elastictransform_prob: 0
    gridistortion_prob: 0
    opticaldistortion_prob: 0
    verticalflip_prob: 0
    horizontalflip_prob: 0
    randomgamma_prob: 0
    CoarseDropout_prob: 0
    RGBShift_prob: 0
    MotionBlur_prob: 0
    MedianBlur_prob: 0
    GaussianBlur_prob: 0
    GaussNoise_prob: 0
    ChannelShuffle_prob: 0




test:
  # TRansUnet+ GALD
  # folds: 
  #   0: 
  #     - 137
  #   1: 
  #     - 149
  #   2: 
  #     - 185
  #   3: 
  #     - 158
  #   4: 
  #     - 101

  # GCPA + GALD
  # folds: 
  #   0: 
  #     - 95 
  #     # - 110
  #   1: 
  #     - 149
  #   2: 
  #     - 149
  #   3: 
  #     - 197
  #   4: 
  #     - 128 
  #     # - 110

  # GCPA + GALDv4
  # folds: 
  #   0: 
  #     - 140
  #   1: 
  #     - 170
  #   2: 
  #     - 149
  #   3: 
  #     - 98
  #   4: 
  #     - 152 

  # Pranetv8
  # folds: 
  #   0: 
  #     - 158
  #   1: 
  #   2: 
  #     - 149
  #   3: 
  #   4: 


  # PranetvGALD
  # folds: 
  #   0: 
  #     - 116
  #   1:
  #     - 197
  #   2: 
  #     - 140
  #   3:
  #     - 140
  #   4:
  #     - 191 

  folds: 
    # 0: 
    #   - 81
    #   - 199
    # 1: 
    #   - 81
    #   - 199
    # 2: 
    #   - 81
    #   - 199
    # 3: 
    #   - 190
    #   - 199
    # 4: 
    #   - 81
    #   - 199
    5: 
      - 239
      - 240
  visualize: True
  visualize_dir: ../results/SCWSRCCA_ISIC_org
  vis_x: 180
  vis_overwrite: True
  dataloader:
    name: ISICDataset
    batchsize: 1
    shuffle : False
    img_size: 352
    pin_memory: True
    drop_last: True

  augment: 
    prob: 0

    Flip_prob: 0
    HueSaturationValue_prob: 0
    RandomBrightnessContrast_prob: 0
    crop_prob: 0

    randomrotate90_prob: 0
    elastictransform_prob: 0
    gridistortion_prob: 0
    opticaldistortion_prob: 0
    verticalflip_prob: 0
    horizontalflip_prob: 0
    randomgamma_prob: 0
    CoarseDropout_prob: 0
    RGBShift_prob: 0
    MotionBlur_prob: 0
    MedianBlur_prob: 0
    GaussianBlur_prob: 0
    GaussNoise_prob: 0
    ChannelShuffle_prob: 0



