dataset:
  data_path: ../data/Kvasir_fold_new
  train_data_path: 
    - ../data/kvasir-seg/TrainDataset
    - ../data/kvasir-seg/ValDataset

    # - ../data/Kvasir_fold_new/fold_3
    # - ../data/Kvasir_fold_new/fold_1
    # - ../data/Kvasir_fold_new/fold_2
    # - ../data/Kvasir_fold_new/fold_4
  test_data_path:
    # - ../data/Kvasir_fold_new/fold_0
    - ../data/kvasir-seg/TestDataset/Kvasir
    # - ../data/kvasir-seg/TestDataset/CVC-ColonDB
    # - ../data/kvasir-seg/TestDataset/CVC-ClinicDB
    # - ../data/kvasir-seg/TestDataset/ETIS-LaribPolypDB
    # - ../data/kvasir-seg/TestDataset/CVC-300
  val_data_path:
    # - ../data/kvasir-seg/TestDataset/Kvasir
    - ../data/kvasir-seg/TestDataset/CVC-ClinicDB

    # - ../data/kvasir-seg/ValDataset
  fold: 5
 
model:
  # save_dir: ../snapshots/noaug_SCWSCCNet_kfold_validate
  # arch: GCPACCNet
  arch: SCWSPSPNet
  
  # SCWSCCNet
  # arch: GCPAGALDNetv8
  # PraNetGALD
  # GCPAGALDNet
  save_from: 150
  start_from: 0
  num_epochs: 200

optimizer:
  name: adam
  lr: 0.0001
  clip: 0.5 
  scheduler: cosine_warmup
  # scheduler: WarmupCosineLrScheduler
  num_warmup_epoch: 8
  loss: structure_loss

train:
  fold: 5
  is_val: True
  size_rates:
    - 0.75
    - 1
    - 1.25
  dataloader:
    name: KvasirDataset
    batchsize: 16
    shuffle : True
    img_size: 448
    pin_memory: True
    drop_last: True
  augment: 
    prob: 0.7
    blur_prob: 0.7
    jitter_prob: 0.7
    rotate_prob: 0.7
    flip_prob: 0.7


test:


  folds: 
    # 0: 
    #   - 81
    #   - 199
    # 1: 
    #   - 81
    #   - 199
    # 2: 
    #   - 81
    #   - 199
    # 3: 
    #   - 190
    #   - 199
    # 4: 
    #   - 81
    #   - 199
    5: 
      - 199
      - 200
  visualize: False
  visualize_dir: ../results/GCPAPSPSmallNet_org
  vis_x: 180
  vis_overwrite: False
  dataloader:
    name: KvasirDataset
    batchsize: 1
    shuffle : False
    img_size: 448
    pin_memory: True
    drop_last: True

  augment: 
    prob: 0
    blur_prob: 0
    jitter_prob: 0
    rotate_prob: 0
    flip_prob: 0

