dataset:
  data_path: ../data/Kvasir_fold_new
  distill_label_path: ../results/SCWSRCCANet_ISICBCDU/PR_SCWSRCCANet/Hard
  # distill_label_path: ../results/SCWSLambdaNet_kfold/fold5/soft_SCWSLambdaNet

  train_data_path: 
    # - ../data/kvasir-seg/TrainDataset
    # - ../data/kvasir-seg/ValDataset
    - ../data/ISIC2018_BCDU/traindataset_256

    # - ../data/Kvasir_fold_new/fold_3
    # - ../data/Kvasir_fold_new/fold_1
    # - ../data/Kvasir_fold_new/fold_2
    # - ../data/Kvasir_fold_new/fold_4
  test_data_path:

    - ../data/ISIC2018_BCDU/testdataset_256

    # - ../data/Kvasir_fold_new/fold_0
    # - ../data/kvasir-seg/TestDataset/Kvasir
    # - ../data/kvasir-seg/TestDataset/CVC-ColonDB
    # - ../data/kvasir-seg/TestDataset/CVC-ClinicDB
    # - ../data/kvasir-seg/TestDataset/ETIS-LaribPolypDB
    # - ../data/kvasir-seg/TestDataset/CVC-300
  val_data_path:
    - ../data/ISIC2018_BCDU/valdataset_256

    # - ../data/kvasir-seg/TestDataset/Kvasir
    # - ../data/kvasir-seg/TestDataset/CVC-ClinicDB

  fold: 5
 
model:
  save_dir: /mnt/data/hungnt/snapshots/SCWSRCCANetDistillation_ISICBCDU
  # arch: SCWSBottleStackNet
  # arch: SCWSLambdaNet
  arch: SCWSRCCANet
  # arch: GCPARCCANet
  
  
  save_from: 180
  start_from: 0
  num_epochs: 300

optimizer:
  name: adam
  lr: 0.0001
  clip: 0.5 
  scheduler: cosine_warmup
  num_warmup_epoch: 8
  loss: distillation_loss

train:
  fold: 5
  is_val: True
  size_rates:
    # - 0.75
    - 1
    - 1.25

  dataloader:
    name: ISICDistillationDataset
    # name: KvasirDistillationDataset
    batchsize: 56
    shuffle : True
    img_size: 256
    pin_memory: True
    drop_last: True
  augment: 
    prob: 0.7

    Flip_prob: 0.7
    HueSaturationValue_prob: 0.7
    RandomBrightnessContrast_prob: 0.7
    crop_prob: 0.7

    randomrotate90_prob: 0.7
    # elastictransform_prob: 0.7
    # gridistortion_prob: 0.7
    # opticaldistortion_prob: 0.7
    # verticalflip_prob: 0.7
    # horizontalflip_prob: 0.7
    # randomgamma_prob: 0.7
    # CoarseDropout_prob: 0.7
    # RGBShift_prob: 0.7
    # MotionBlur_prob: 0.7
    # MedianBlur_prob: 0.7
    # GaussianBlur_prob: 0.7
    # GaussNoise_prob: 0.7
    # ChannelShuffle_prob: 0.7
test:
  folds: 
    5: 
      - 151
      - 200
  dev: cuda
  visualize: False
  visualize_dir: ../results/SCWSLambdaNet_kfold
  vis_x: 180
  vis_overwrite: False
  dataloader:
    name: KvasirDataset
    batchsize: 1
    shuffle : False
    img_size: 256
    pin_memory: True
    drop_last: True

  augment: 
    prob: 0

    Flip_prob: 0
    HueSaturationValue_prob: 0
    RandomBrightnessContrast_prob: 0
    crop_prob: 0

    # randomrotate90_prob: 0
    # elastictransform_prob: 0
    # gridistortion_prob: 0
    # opticaldistortion_prob: 0
    # verticalflip_prob: 0
    # horizontalflip_prob: 0
    # randomgamma_prob: 0
    # CoarseDropout_prob: 0
    # RGBShift_prob: 0
    # MotionBlur_prob: 0
    # MedianBlur_prob: 0
    # GaussianBlur_prob: 0
    # GaussNoise_prob: 0
    # ChannelShuffle_prob: 0

